name: Publish to crates.io

on:
  push:
    tags: ['v*']

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write # Required for OIDC token exchange
    
    steps:
      - uses: actions/checkout@v4
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: cargo publish -p immediate_stats_macros
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - run: cargo publish -p immediate_stats
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
