name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Build with features
      run: cargo build --all-features --verbose
    - name: Test with features
      run: cargo test --all-features --verbose
    - name: Check format
      run: cargo fmt --check
